### ISSUE TITLE
error when gaining skill

### ISSUE THREAD

**Issue by Nick5M420** [Kingsage311/qb-skillz#2]
![image](https://user-images.githubusercontent.com/95560411/163808944-cda3f20e-f63c-42f8-82d2-6a4d64ba0cf4.png)

**Comment by milotiro95** [comment]
Same not working

**Comment by flitzx** [comment]
Also having the same problem

**Comment by Kingsage311** [comment]
This should be fixed now

**Comment by Kingsage311** [comment]
Confirmed fixed please update to fix this
