### ISSUE TITLE
at the bottom of the ocean

### ISSUE THREAD

**Issue by Maxryodric** [Kingsage311/qb-skillz#5]
the character drowned and you can lie down until you get tired of improving the skill
![skil3](https://user-images.githubusercontent.com/99089233/168968162-fc48af30-6c03-42bd-99a0-e2e93457f46e.jpg)
![skil2](https://user-images.githubusercontent.com/99089233/168968164-116c11d0-985c-4fb7-b6dc-550289ab13b4.jpg)
![skil1](https://user-images.githubusercontent.com/99089233/168968168-e11e98a6-9463-4495-acbb-39407867896e.jpg)
![skil](https://user-images.githubusercontent.com/99089233/168968171-88f2df2c-d191-4165-9d40-0b8ba16ff5e0.jpg)

**Comment by Kingsage311** [comment]
Seems like a easy fix ill get to this soon

**Comment by Maxryodric** [comment]
> Seems like a easy fix ill get to this soon

waiting for update)

**Comment by Kingsage311** [comment]
Please pull the latest update and let me know it is fixed seemed to fix it with my testing

**Comment by Maxryodric** [comment]
> Please pull the latest update and let me know it is fixed seemed to fix it with my testing

checked it works very **well**
